// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdszoeqfgqmlrukgeemb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdkc3pvZXFmZ3FtbHJ1a2dlZW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODA3ODcsImV4cCI6MjA2NDM1Njc4N30.2DooYSYKInpu63yC9aWxr3z1XL8PntAwowWgr7zugPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);