
name: Android Build (Capacitor)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Java setup
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          which java
          javac -version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            android/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install npm dependencies
        run: |
          npm ci --legacy-peer-deps --prefer-offline --no-audit
          npm ls

      - name: Build web assets
        run: |
          npm run build
          ls -la dist/

      - name: Sync Capacitor (without build)
        run: |
          npx cap sync android
          ls -la android/

      - name: Verify Android project structure
        working-directory: android
        run: |
          echo "Checking Android project structure..."
          ls -la
          ls -la app/
          if [ ! -f "gradlew" ]; then
            echo "Error: gradlew not found"
            exit 1
          fi
          chmod +x gradlew

      - name: Validate Android project
        working-directory: android
        run: |
          ./gradlew --version
          ./gradlew projects
          ./gradlew tasks --group="android" | head -20

      - name: Clean Android project
        working-directory: android
        run: |
          ./gradlew clean --stacktrace
          ./gradlew --stop

      - name: Build Android APK (Debug)
        working-directory: android
        run: |
          ./gradlew assembleDebug --stacktrace --info --no-daemon
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m -Dorg.gradle.daemon=false"

      - name: Verify APK creation
        run: |
          if [ -f "android/app/build/outputs/apk/debug/app-debug.apk" ]; then
            ls -la android/app/build/outputs/apk/debug/
            file android/app/build/outputs/apk/debug/app-debug.apk
          else
            echo "APK not found, listing build directory structure..."
            find android/app/build -name "*.apk" -o -name "*.aab" 2>/dev/null || echo "No APK/AAB files found"
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.sha }}
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ github.sha }}
          path: |
            android/app/build/reports/
            android/build/reports/
            android/app/build/tmp/
          retention-days: 7
          if-no-files-found: ignore
