name: Android Build (Capacitor)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Java setup
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          which java

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install npm dependencies & build web assets
        run: |
          npm ci
          npm run build
          npx cap sync android

      - name: Stop Gradle daemon and clean build
        working-directory: android
        run: |
          ./gradlew --stop
          ./gradlew clean

      - name: Build Android APK (Debug)
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
